### PR TITLE
Authorization

### PR DESCRIPTION
**Pull request by felixDev22**
Hi There 👋

**In this repo : Project requirements**

We have done the following:

- [x]  Installed CanCanCan in your project.
-  Added a role column to the users table.
- A user can delete a post if it is theirs or if they have an admin role (column role has value "admin").
- User post deleting functionality. Added the "Delete" button to the view and make sure that only              authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin").
- Used CanCanCan for this authorization.
- Implement the comment deleting functionality. Added the "Delete" button to the view and made sure that  only authorized users can see it.

### CODE REVIEW

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @felixDev22 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that Required you to work with your partner. kindly collaborate with your partner and resubmit. 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by felixDev22** [comment]
Hi @tufoinnkuo10 
I had raised my concerns regarding my coding partner, due to his noncommittal or low contribution to the project. 

firefox_sH67mikXJg
firefox_H47dDXAsgU
slack_y0YtQAq4VF

PLEASE REVIEW!!.....I spoke to him and tried to persuade him, my hopes were that he will be available...and make more contributions.....We still have one more pairing to do....if he will not participate fully....please allow me to complete the remaining activity.....Thank you.

**Comment by felixDev22** [comment]
Hi @tufoinnkuo10 as per our conversation on Zoom, I have attached above the letter concerning low participation of my partner...please consider and review...

Thank you.

**Review by Owusu-Desmond — APPROVED** [review]
Hi @felixDev22 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by felixDev22** [comment]
Thank you so much.

**Pull request merged**
