### PR TITLE
Devise

### PR DESCRIPTION
**Pull request by felixDev22**
Hi There 👋 

**In this repo: Project requirements**
 
- [x]  Removed current_user method in ApplicationController
- [x]  Installed and setup devise to do the following
        - Can register a new user.
        - User logs in with a combination of email and password.
        - Hashed password should be stored in the database.
        - Ask for confirmation of email.
        - Can reset password.

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Submission :red_circle:

invalid-submission

## Hey @felixDev22 :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes :recycle:

- [ ] It would be nice if you ask your partner to make commits in this pull request since this is a pair-programming activity :+1:

**Comment by felixDev22** [comment]
Hello @HAMMAS-SALEEM,
I'm having some trouble reaching my partner today. Despite attempting to contact him through various means, such as phone, Slack, and Zoom, I haven't been successful in getting a response.

**Comment by HAMMAS-SALEEM** [comment]
Hey @felixDev22 I hope you are doing well.

By the way, you have mentioned that you reported this to student success. Once student success allows you to proceed then you can submit this pull request again and it will be reviewed Inshallah

**Review by uwadonat — APPROVED** [review]
## Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Good pull request message ✔️
- Good project structure ✔️
- No linter error ✔️
- professional pull request message ✔️
approval1


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
